const ActionTypes = {
  DOWNLOAD_FRESH_NEWS: "DOWNLOAD_FRESH_NEWS",
  UPDATE_RATING: "UPDATE_RATING",
  UPDATE_VIEWERS: "UPDATE_VIEWERS",
  FILTER_BY_TITLE: "FILTER_BY_TITLE",
  DOWNLOAD_ERROR: "DOWNLOAD_ERROR",
};

export default ActionTypes;