const ActionTypes = {
  RATE_NEWS: "RATE_NEWS",
  FIND_BY_TITLE: "FIND_BY_TITLE",
  UPDATE_NEWS: "UPDATE_NEWS",
  DOWNLOAD_FRESH_NEWS: "DOWNLOAD_FRESH_NEWS",
  UPDATE_RATING: "UPDATE_RATING",
  UPDATE_VIEWERS: "UPDATE_VIEWERS",
  DOWNLOAD_ERROR: "DOWNLOAD_ERROR",
};

export default ActionTypes;