const C = {
  ADD_NEWS: "ADD_NEWS",
  RATE_NEWS: "RATE_NEWS",
  INITIAL_STATE: "INITIAL_STATE",
  UPDATE_NEWS: "UPDATE_NEWS",
  DOWNLOAD_FRESH_NEWS: "DOWNLOAD_FRESH_NEWS",
  UPDATE_RATING: "UPDATE_RATING",
  UPDATE_VIEWERS: "UPDATE_VIEWERS",
};

export default C;